spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/backend
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true